"""
PCAP StoryTeller - Analytics Service
-----------------------------------
This service takes the raw list of network events and calculates 
important statistics (Top Talkers, Common Ports, etc.) for the 
Dashboard charts.
"""

from collections import defaultdict
from core.logger import logger

class AnalyticsService:
    """
    Provides data aggregation logic to turn individual events into 
    meaningful network summaries.
    """

    @staticmethod
    def analyze_events(event_list):
        """
        Processes a list of forensic events to produce statistical counters.
        
        Args:
            event_list (list): The 'events' list generated by the PCAPParser.
            
        Returns:
            dict: Aggregated stats ready for Chart.js on the frontend.
        """
        logger.info(f"Starting forensic analytics on {len(event_list)} events")
        
        # Initialize our counters (using defaultdict to simplify incrementing)
        type_frequency = {}              # Count of DNS vs HTTP vs TCP etc.
        source_ip_counts = defaultdict(int) # Who is sending the most data?
        dest_ip_counts = defaultdict(int)   # Who is receiving the most data?
        port_frequency = defaultdict(int)   # Which Ports ("doors") are most common?
        protocol_frequency = defaultdict(int) # Mix of TLS vs ICMP vs others
        
        # Step-by-Step: Loop through every event found in the PCAP
        for event in event_list:
            # 1. Track the frequency of each category/type
            event_type = event.get('type', 'Unknown')
            type_frequency[event_type] = type_frequency.get(event_type, 0) + 1
            
            # 2. Extract and count IP address activity
            source_ip = event.get('source_ip')
            destination_ip = event.get('dest_ip')
            
            if source_ip: 
                source_ip_counts[source_ip] += 1
            if destination_ip: 
                dest_ip_counts[destination_ip] += 1
            
            # 3. Analyze specific protocol details (Ports and Sub-protocols)
            details = event.get('details', {})
            
            destination_port = details.get('dport')
            if destination_port: 
                # We store port numbers as strings for clean JSON keys
                port_frequency[str(destination_port)] += 1
            
            protocol_name = details.get('protocol', 'Unknown')
            protocol_frequency[protocol_name] += 1
        
        # Final Step: Package and sort the results for visual presentation
        return {
            'event_counts': type_frequency,
            
            # Find the top 10 sources sending the most traffic
            'top_sources': sorted(source_ip_counts.items(), key=lambda x: x[1], reverse=True)[:10],
            
            # Find the top 10 destinations receiving the most traffic
            'top_destinations': sorted(dest_ip_counts.items(), key=lambda x: x[1], reverse=True)[:10],
            
            # Top 15 most active network ports
            'port_distribution': dict(sorted(port_frequency.items(), key=lambda x: x[1], reverse=True)[:15]),
            
            # Overall distribution of all detected protocols
            'protocol_distribution': dict(sorted(protocol_frequency.items(), key=lambda x: x[1], reverse=True)),
            
            'total_events': len(event_list),
            'unique_source_count': len(source_ip_counts),
            'unique_dest_count': len(dest_ip_counts)
        }
